# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicolas Garavito Camargo
email: jngaravitoc@email.arizona.edu
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/Garavito-Camargo" # the subpath of your site, e.g. /blog
url: "https://jngaravitoc.github.io" # the base hostname & protocol for your site
twitter_username: garavito_nico
github_username:  jngaravitoc

# Build settings
sass:
    sass_dir: _sass
    include: ['_pages']
markdown: kramdown
