title: Nicolas Garavito Camargo
url: "https://ankitsultana.com"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"
remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Nicolas Garavito-Camargo"
   link: "/about/"
 - name: "Resume"
   link: "resume.pdf"
