title: Nicolas Garavito Camargo
url: "https://ankitsultana.com"
baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"
remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "CV/publications"
   link: "cv_pub"
 - name: "Outreach & Community"
   link: "outreach"
